ID: 2026Y-02M-01D-08h59m33s_YXcS
PID: 1739928
START_DATETIME: 2026-02-01 08:59:33.911088
FILE: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/10_programmatic_verification.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/10_programmatic_verification_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/10_programmatic_verification_out/RUNNING/2026Y-02M-01D-08h59m33s_YXcS-main
ARGS: {}
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:59:36.359040
RUN_DURATION: 00:00:02
