ID: 2026Y-02M-01D-08h57m37s_gVzK
PID: 1733876
START_DATETIME: 2026-02-01 08:57:37.086414
FILE: /home/ywatanabe/proj/scitex-python/examples/scitex/verify/08_analyze.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/08_analyze_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/08_analyze_out/RUNNING/2026Y-02M-01D-08h57m37s_gVzK-main
ARGS:
    input_file:
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:57:39.806935
RUN_DURATION: 00:00:02
