ID: 2026Y-02M-01D-08h58m57s_6bY9
PID: 1738070
START_DATETIME: 2026-02-01 08:58:57.669393
FILE:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification.py
SDIR_OUT:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out
SDIR_RUN:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out/RUNNING/2026Y-02M-01D-08h58m57s_6bY9-main
ARGS:
    action: visualize
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:59:14.922587
RUN_DURATION: 00:00:17
