ID: 2026Y-02M-01D-08h55m46s_0KFa
PID: 1727256
START_DATETIME: 2026-02-01 08:55:46.469088
FILE:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/02_preprocess_a.py
SDIR_OUT:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/02_preprocess_a_out
SDIR_RUN:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/02_preprocess_a_out/RUNNING/2026Y-02M-01D-08h55m46s_0KFa-main
ARGS:
    input_file:
    config_file:
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:55:49.034907
RUN_DURATION: 00:00:02
