ID: 2026Y-02M-01D-08h56m42s_rZAC
PID: 1730767
START_DATETIME: 2026-02-01 08:56:42.257148
FILE: /home/ywatanabe/proj/scitex-python/examples/scitex/verify/05_source_c.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/05_source_c_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/05_source_c_out/RUNNING/2026Y-02M-01D-08h56m42s_rZAC-main
ARGS:
    n_samples: 250
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:56:44.914659
RUN_DURATION: 00:00:02
