ID: 2026Y-02M-01D-08h57m19s_yQu9
PID: 1732920
START_DATETIME: 2026-02-01 08:57:19.291659
FILE: /home/ywatanabe/proj/scitex-python/examples/scitex/verify/07_merge.py
SDIR_OUT: /home/ywatanabe/proj/scitex-python/examples/scitex/verify/07_merge_out
SDIR_RUN:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/07_merge_out/RUNNING/2026Y-02M-01D-08h57m19s_yQu9-main
ARGS:
    input_a:
    input_b:
    input_c:
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:57:19.122225
RUN_DURATION: 00:00:00
