ID: 2026Y-02M-01D-08h56m04s_MI1c
PID: 1728613
START_DATETIME: 2026-02-01 08:56:04.984340
FILE: /home/ywatanabe/proj/scitex-python/examples/scitex/verify/03_source_b.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/03_source_b_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/03_source_b_out/RUNNING/2026Y-02M-01D-08h56m04s_MI1c-main
ARGS:
    n_samples: 300
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:56:07.581206
RUN_DURATION: 00:00:02
