ID: 2026Y-02M-01D-08h58m39s_fn70
PID: 1737018
START_DATETIME: 2026-02-01 08:58:39.241095
FILE:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification.py
SDIR_OUT:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out
SDIR_RUN:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out/RUNNING/2026Y-02M-01D-08h58m39s_fn70-main
ARGS:
    action: break
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:58:41.696930
RUN_DURATION: 00:00:02
