ID: 2026Y-02M-01D-08h56m59s_89Fn
PID: 1731763
START_DATETIME: 2026-02-01 08:56:59.235099
FILE: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/06_preprocess_c.py
SDIR_OUT: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/06_preprocess_c_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/06_preprocess_c_out/RUNNING/2026Y-02M-01D-08h56m59s_89Fn-main
ARGS:
    input_file:
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:57:01.792482
RUN_DURATION: 00:00:02
