ID: 2026Y-02M-01D-08h57m56s_CZTP
PID: 1734907
START_DATETIME: 2026-02-01 08:57:56.285882
FILE:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification.py
SDIR_OUT:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out
SDIR_RUN:
    /home/ywatanabe/proj/scitex-python/examples/scitex/verify/09_demo_verification_out/RUNNING/2026Y-02M-01D-08h57m56s_CZTP-main
ARGS:
    action: rerun
EXIT_STATUS: 0
END_DATETIME: 2026-02-01 08:58:20.005792
RUN_DURATION: 00:00:23
